parameters:
    starcraft_connection_layer.class: petrepatrasc\StarcraftConnectionLayerBundle\OverviewService

services:
    starcraft_connection_layer:
        class: %starcraft_connection_layer.class%
